In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
data = pd.read_csv('D:/Data/PM2.5predictions/train.csv', encoding='utf8')

In [7]:
data.head(10)

,日期,測站,測項,0,1,2,3,4,5,6,...,14,15,16,17,18,19,20,21,22,23
0,2014/1/1,豐原,AMB_TEMP,14,14,14,13,12,12,12,...,22,22,21,19,17,16,15,15,15,15
1,2014/1/1,豐原,CH4,1.8,1.8,1.8,1.8,1.8,1.8,1.8,...,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8,1.8
2,2014/1/1,豐原,CO,0.51,0.41,0.39,0.37,0.35,0.3,0.37,...,0.37,0.37,0.47,0.69,0.56,0.45,0.38,0.35,0.36,0.32
3,2014/1/1,豐原,NMHC,0.2,0.15,0.13,0.12,0.11,0.06,0.1,...,0.1,0.13,0.14,0.23,0.18,0.12,0.1,0.09,0.1,0.08
4,2014/1/1,豐原,NO,0.9,0.6,0.5,1.7,1.8,1.5,1.9,...,2.5,2.2,2.5,2.3,2.1,1.9,1.5,1.6,1.8,1.5
5,2014/1/1,豐原,NO2,16,9.2,8.2,6.9,6.8,3.8,6.9,...,11,11,22,28,19,12,8.1,7,6.9,6
6,2014/1/1,豐原,NOx,17,9.8,8.7,8.6,8.5,5.3,8.8,...,14,13,25,30,21,13,9.7,8.6,8.7,7.5
7,2014/1/1,豐原,O3,16,30,27,23,24,28,24,...,65,64,51,34,33,34,37,38,38,36
8,2014/1/1,豐原,PM10,56,50,48,35,25,12,4,...,52,51,66,85,85,63,46,36,42,42
9,2014/1/1,豐原,PM2.5,26,39,36,35,31,28,25,...,36,45,42,49,45,44,41,30,24,13

In [8]:
pm2_5 = data[data['測項']=='PM2.5'].ix[:, 3:]

C:\Users\Anaconda3\lib\site-packages\ipykernel\__main__.py:1: DeprecationWarning:
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#deprecate_ix
  if __name__ == '__main__':

In [9]:
pm2_5.head(10)

,0,1,2,3,4,5,6,7,8,9,...,14,15,16,17,18,19,20,21,22,23
9,26,39,36,35,31,28,25,20,19,30,...,36,45,42,49,45,44,41,30,24,13
27,21,23,30,30,22,18,13,13,11,22,...,53,43,43,45,46,32,16,19,22,26
45,19,25,27,20,16,14,15,8,4,9,...,32,36,34,45,40,41,23,29,23,37
63,27,27,14,20,22,24,26,33,48,50,...,62,55,56,67,78,83,90,75,85,82
81,80,80,76,81,75,66,70,65,66,57,...,64,73,57,57,53,70,70,60,68,66
99,66,55,46,46,46,42,35,35,40,45,...,62,59,61,50,60,62,62,50,45,43
117,41,32,35,31,33,25,36,28,33,29,...,62,61,47,54,57,59,61,43,39,38
135,48,53,60,60,52,47,45,50,43,40,...,35,36,36,32,33,33,34,21,15,13
153,18,15,9,9,14,15,20,16,23,16,...,20,20,20,18,18,22,15,11,1,1
171,6,7,7,0,0,1,1,7,7,8,...,23,20,18,15,16,10,6,11,22,28

In [27]:
pm2_5.shape

(240, 24)

In [46]:
tempxlist = []
tempylist = []

下面设计算法，需要加强

In [47]:
for i in range(15):
    tempx = pm2_5.iloc[:, i:i+9]                      #是个DataFrame
    tempx.columns = np.array(range(9))        #设置DataFrame的columns
    tempy = pm2_5.iloc[:, i+9]
    tempy.columns = ['1']
    tempxlist.append(tempx)                         #是个List
    tempylist.append(tempy)

In [48]:
xdata = pd.concat(tempxlist)                     #xdata是个DataFrame，把15个小的DF连接了起来
x = np.array(xdata, float)                            #DataFrame转换成np.array
x

array([[ 26.,  39.,  36., ...,  25.,  20.,  19.],
       [ 21.,  23.,  30., ...,  13.,  13.,  11.],
       [ 19.,  25.,  27., ...,  15.,   8.,   4.],
       ...,
       [ 31.,  31.,  36., ...,  39.,  36.,  24.],
       [ 21.,  21.,  19., ...,  11.,   0.,   7.],
       [  1.,   7.,  24., ...,  28.,  17.,  24.]])

In [49]:
ydata = pd.concat(tempylist)
y = np.array(ydata, float)
y

array([ 30.,  22.,   9., ...,  23.,   7.,  29.])

In [50]:
print('{},{}'.format(x.shape, y.shape))

(3600, 9),(3600,)

In [51]:
# 原数据240行，现有数据3600 = 240*15，是因为按照时间序列拆分前9个小时的数据作为预测第10个小时的依据。

自此，训练数据就准备好了，可以使用回归模型去完成训练